#!/usr/bin/env python3
"""
Ethereum Address Validation Script

Purpose: Verify that Ethereum addresses generated by our tool match web3.py derivation
Usage: python3 validate_ethereum.py <private_key_hex>

Example:
    python3 validate_ethereum.py e1d53f00d25ea0557b353829a85bb256973ea5d89c7b49f5346c27b49abfddaa
"""

import sys
import os

try:
    from web3 import Web3
except ImportError:
    print("Error: web3 library not installed")
    print("Install with: pip3 install web3")
    sys.exit(1)


def validate_ethereum_address(private_key_hex, expected_address=None):
    """
    Validate Ethereum address derivation.
    
    Args:
        private_key_hex: Private key as hex string (without 0x prefix)
        expected_address: Expected checksum address for verification
        
    Returns:
        dict with validation results
    """
    
    # Ensure private key has 0x prefix for web3.py
    if not private_key_hex.startswith('0x'):
        private_key_hex = '0x' + private_key_hex
    
    try:
        # Create web3 instance
        w3 = Web3()
        
        # Derive account from private key
        account = w3.eth.account.from_key(private_key_hex)
        
        # Get checksummed address
        address = account.address
        checksum_address = w3.to_checksum_address(address)
        
        result = {
            'private_key': private_key_hex,
            'address_lowercase': address.lower(),
            'address_checksum': checksum_address,
            'public_key_hex': account.key.hex() if hasattr(account, 'key') else 'N/A',
            'valid': True,
            'error': None
        }
        
        # Verify checksum if expected address provided
        if expected_address:
            if checksum_address == expected_address:
                result['matches_expected'] = True
                result['message'] = "✅ Address matches expected value!"
            else:
                result['matches_expected'] = False
                result['message'] = f"❌ Address mismatch!\nExpected: {expected_address}\nGot:      {checksum_address}"
        
        return result
        
    except Exception as e:
        return {
            'valid': False,
            'error': str(e),
            'message': f"❌ Error: {e}"
        }


def validate_solana_address(seed_hex, expected_address=None):
    """
    Validate Solana address (requires solders library).
    
    Args:
        seed_hex: Seed as hex string
        expected_address: Expected address for verification
        
    Returns:
        dict with validation results
    """
    
    try:
        from solders.keypair import Keypair
        
        # Convert hex seed to bytes
        seed_bytes = bytes.fromhex(seed_hex)
        
        # Create keypair
        keypair = Keypair.from_secret_key(seed_bytes + seed_bytes)  # Solana format
        
        address = str(keypair.pubkey())
        
        result = {
            'seed': seed_hex,
            'address': address,
            'valid': True,
            'error': None
        }
        
        if expected_address:
            if address == expected_address:
                result['matches_expected'] = True
                result['message'] = "✅ Address matches expected value!"
            else:
                result['matches_expected'] = False
                result['message'] = f"❌ Address mismatch!\nExpected: {expected_address}\nGot:      {address}"
        
        return result
        
    except ImportError:
        return {
            'valid': False,
            'error': 'solders library not installed',
            'message': 'Run: pip3 install solders'
        }
    except Exception as e:
        return {
            'valid': False,
            'error': str(e),
            'message': f"❌ Error: {e}"
        }


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        print("\nUsage examples:")
        print("  python3 validate_ethereum.py e1d53f00d25ea0557b353829a85bb256973ea5d89c7b49f5346c27b49abfddaa")
        print("  python3 validate_ethereum.py e1d53f00d25ea0557b353829a85bb256973ea5d89c7b49f5346c27b49abfddaa 0x7160a854BA41D4F3099C6a366bA0201f7756E719")
        sys.exit(1)
    
    private_key = sys.argv[1]
    expected_address = sys.argv[2] if len(sys.argv) > 2 else None
    
    print("=" * 70)
    print("Ethereum Address Validation")
    print("=" * 70)
    print()
    
    result = validate_ethereum_address(private_key, expected_address)
    
    if result['valid']:
        print(f"Private Key:        {result['private_key']}")
        print(f"Address (lowercase): {result['address_lowercase']}")
        print(f"Address (checksum): {result['address_checksum']}")
        print()
        if expected_address:
            print(result['message'])
            if result.get('matches_expected'):
                print("Status: ✅ PASS")
                return 0
            else:
                print("Status: ❌ FAIL")
                return 1
    else:
        print(f"Error: {result['error']}")
        print("Status: ❌ FAIL")
        return 1
    
    return 0


if __name__ == '__main__':
    sys.exit(main())
